default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['POSTGRES_DATABASE'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>

development:
  <<: *default

test:
  <<: *default
  database: patient_management_test

staging:
  <<: *default
  database: patient_management_staging

pre_production:
  <<: *default
  database: patient_management_pre_production

production:
  <<: *default
  database: patient_management_production
